<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $customers = [
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Toyota Motor',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'               => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 938-652-9469',
        'fax'                 => '',
        'email'               => 'ToyotaMotor@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => 1,
        'name'                => 'Toyota Motor 1.1',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'               => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 938-652-9469',
        'fax'                 => '',
        'email'               => 'ToyotaMotor@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => 1,
        'name'                => 'Toyota Motor 1.2',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'               => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 938-652-9469',
        'fax'                 => '',
        'email'               => 'ToyotaMotor@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => 1,
        'name'                => 'Toyota Motor 1.3',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'               => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 938-652-9469',
        'fax'                 => '',
        'email'               => 'ToyotaMotor@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Honda Motor',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'               => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 878-652-9469',
        'fax'                 => '',
        'email'               => 'HondaMotor@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Mitsubishi',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'               => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 8348-652-9469',
        'fax'                 => '',
        'email'               => 'Mitsubishi@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Japan Post Holdings',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'               => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-931',
        'fax'                 => '',
        'email'               => 'JapanPostHoldings@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Nippon Telegraph & Telephone',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'NipponTelegraphTelephone@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Itochu',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Itochu@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Nissan Motor',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'NissanMotor@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'SoftBankGroup',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'SoftBankGroup@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Hitachi',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Hitachi@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'AEON',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'AEONe@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Sony',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Sony@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'ENEOS Holdings',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'ENEOSHoldings@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Nippon Life Insurance',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'NipponLifeInsurance@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Panasonic',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Panasonic@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Mitsubishi UFJ Financial Group',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'MitsubishiUFJFinancialGroup@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Dai-ichi Life Holdings',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'DaiichiLifeHoldings@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Mitsui',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Mitsui@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Marubeni',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Marubeni@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Toyota Tsusho',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'ToyotaTsusho@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Seven & I Holdings',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'SevenIHoldings@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Tokyo Electric Power',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'TokyoElectricPower@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Nippon Steel Corporation',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'NipponSteelCorporation@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Tokio Marine Holdings',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'TokioMarineHoldings@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Idemitsu Kosan',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'IdemitsuKosan@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Sumitomo Mitsui Financial Group',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'SumitomoMitsuiFinancialGroup@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Sumitomo',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Sumitomo@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'KDDI',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'KDDI@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'MS&AD Insurance Group Holdings',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'MSADInsuranceGroupHoldings@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Denso',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'Denso@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Mitsubishi Electric',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'MitsubishiElectric@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ],
      [
        // 'user_id'             => 1,
        'parent_id'           => null,
        'name'                => 'Daiwa House Industry',
        'kana_name'           => '',
        'business_name'       => '',
        'short_name'          => '',
        'image'                => '',
        'building_name'       => '',
        'street'              => '',
        'district'            => '',
        'province'            => '',
        'address'             => '',
        'post_code'           => '',
        'phone'               => '1 808-652-9432',
        'fax'                 => '',
        'email'               => 'DaiwaHouseIndustry@gmail.com',
        'website'             => '',
        'charter_capital'     => 1000,
        'founding'            => new Carbon('2020-1-5'),
        'number_of_employees' => 500,
        'revenue'             => 275288,
        'remark'              => '',
      ]
    ];

    DB::table('customers')->insert($customers);
  }
}
